<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta http-equiv="Content-Style-Type" content="text/css">
  <title></title>
  <meta name="Generator" content="Cocoa HTML Writer">
  <meta name="CocoaVersion" content="2299.6">
  <style type="text/css">
    p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica}
    p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 12.0px Helvetica; min-height: 14.0px}
  </style>
</head>
<body>
<p class="p1">import java.util.*;</p>
<p class="p1">public class MyProgram</p>
<p class="p1">{</p>
<p class="p1"><span class="Apple-converted-space">    </span>static double AtkCalculator(int level, double batk){</p>
<p class="p1"><span class="Apple-converted-space">           </span>double number = 5;</p>
<p class="p1"><span class="Apple-converted-space">           </span>for(int i = 1;i&lt;level;i++){</p>
<p class="p1"><span class="Apple-converted-space">               </span>number = number+batk*0.02;</p>
<p class="p1"><span class="Apple-converted-space">           </span>}</p>
<p class="p1"><span class="Apple-converted-space">           </span>return number;</p>
<p class="p2"><span class="Apple-converted-space">            </span></p>
<p class="p1"><span class="Apple-converted-space">       </span>}</p>
<p class="p1"><span class="Apple-converted-space">    </span>static double HPCalculator(int level, double bHealth){</p>
<p class="p1"><span class="Apple-converted-space">        </span>double number = 11;</p>
<p class="p1"><span class="Apple-converted-space">        </span>for(int i=1;i&lt;level;i++){</p>
<p class="p1"><span class="Apple-converted-space">            </span>number = number+((bHealth*0.02)+1);</p>
<p class="p1"><span class="Apple-converted-space">        </span>}</p>
<p class="p1"><span class="Apple-converted-space">        </span>return number;</p>
<p class="p1"><span class="Apple-converted-space">    </span>}</p>
<p class="p1"><span class="Apple-converted-space">    </span>static double dfCalculator(int level, double df){</p>
<p class="p1"><span class="Apple-converted-space">        </span>double number = 5;</p>
<p class="p1"><span class="Apple-converted-space">        </span>for(int i = 1;i&lt;level;i++){</p>
<p class="p1"><span class="Apple-converted-space">            </span>number = number+df*0.02;</p>
<p class="p2"><span class="Apple-converted-space">            </span></p>
<p class="p1"><span class="Apple-converted-space">        </span>}</p>
<p class="p1"><span class="Apple-converted-space">        </span>return number;</p>
<p class="p1"><span class="Apple-converted-space">    </span>}</p>
<p class="p1"><span class="Apple-converted-space">    </span>public static void main(String[] args)</p>
<p class="p1"><span class="Apple-converted-space">    </span>{</p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p1"><span class="Apple-converted-space">       </span>//base hp and attack inputters as well as level stuff</p>
<p class="p1"><span class="Apple-converted-space">       </span>Scanner scan = new Scanner(System.in);</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Input the base HP of your first pokemon");</p>
<p class="p1"><span class="Apple-converted-space">       </span>double bhp1 = scan.nextDouble();</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Input the base attack of your first pokemon");</p>
<p class="p1"><span class="Apple-converted-space">       </span>double batk1=scan.nextDouble();</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Input the level of your pokemon");</p>
<p class="p1"><span class="Apple-converted-space">       </span>int lvlNumeroUno = scan.nextInt();</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Enter the defense of your first pokemon: ");</p>
<p class="p1"><span class="Apple-converted-space">       </span>double bdf1 = scan.nextDouble();</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Enter the typing of your first pokemon: ");</p>
<p class="p1"><span class="Apple-converted-space">       </span>scan.nextLine();</p>
<p class="p1"><span class="Apple-converted-space">       </span>String typing1 = scan.nextLine();</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("What is the name of your first pokemon: ");</p>
<p class="p1"><span class="Apple-converted-space">       </span>String name1 = scan.nextLine();</p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Input the base HP of your second pokemon");</p>
<p class="p1"><span class="Apple-converted-space">       </span>double bhp2 = scan.nextDouble();</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Input the base attack of your second pokemon");</p>
<p class="p1"><span class="Apple-converted-space">       </span>double batk2 = scan.nextDouble();</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Input the level of your second pokemon");</p>
<p class="p1"><span class="Apple-converted-space">       </span>int lvlNumeroDos = scan.nextInt();</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Enter the defense of your second pokemon: ");</p>
<p class="p1"><span class="Apple-converted-space">       </span>double bdf2 = scan.nextDouble();</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Enter the typing of your second pokemon: ");</p>
<p class="p1"><span class="Apple-converted-space">       </span>scan.nextLine();</p>
<p class="p1"><span class="Apple-converted-space">       </span>String typing2 = scan.nextLine();</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("What is the name of your second pokemon: ");</p>
<p class="p1"><span class="Apple-converted-space">       </span>String name2 = scan.nextLine();</p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p1"><span class="Apple-converted-space">       </span>if(bhp1 == 44 &amp;&amp; batk1 ==48){</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">              </span>_,........__");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">            </span>,-'<span class="Apple-converted-space">            </span>\"`-.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">          </span>,' <span class="Apple-converted-space">                  </span>`-.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">        </span>,'<span class="Apple-converted-space">                        </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">      </span>,' <span class="Apple-converted-space">                          </span>.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">      </span>.'\\ <span class="Apple-converted-space">              </span>,\"\". <span class="Apple-converted-space">      </span>`");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">    </span>._.'| <span class="Apple-converted-space">            </span>/ |<span class="Apple-converted-space">  </span>` <span class="Apple-converted-space">      </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">    </span>| <span class="Apple-converted-space">  </span>|<span class="Apple-converted-space">            </span>`-.'<span class="Apple-converted-space">  </span>|| <span class="Apple-converted-space">      </span>`.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">    </span>| <span class="Apple-converted-space">  </span>|<span class="Apple-converted-space">            </span>'-._,'|| <span class="Apple-converted-space">      </span>| \\");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">    </span>.`.,' <span class="Apple-converted-space">            </span>`..,'.' <span class="Apple-converted-space">      </span>, |`-.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">    </span>l <span class="Apple-converted-space">                      </span>.'`.<span class="Apple-converted-space">  </span>_/<span class="Apple-converted-space">  </span>| <span class="Apple-converted-space">  </span>`.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">    </span>`-.._'- <span class="Apple-converted-space">  </span>,<span class="Apple-converted-space">          </span>_ _' <span class="Apple-converted-space">  </span>-\" \\<span class="Apple-converted-space">  </span>. <span class="Apple-converted-space">    </span>`");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("`.\"\"\"\"\"'-.`-...,---------',' <span class="Apple-converted-space">        </span>`. `....__.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(".'<span class="Apple-converted-space">        </span>`\"-..___<span class="Apple-converted-space">      </span>__,'\\<span class="Apple-converted-space">          </span>\\<span class="Apple-converted-space">  </span>\\ <span class="Apple-converted-space">    </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("\\_ .<span class="Apple-converted-space">          </span>| <span class="Apple-converted-space">  </span>`\"\"\"\"'<span class="Apple-converted-space">    </span>`. <span class="Apple-converted-space">          </span>. \\ <span class="Apple-converted-space">    </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">  </span>`.<span class="Apple-converted-space">          </span>|<span class="Apple-converted-space">              </span>`.<span class="Apple-converted-space">          </span>|<span class="Apple-converted-space">  </span>. <span class="Apple-converted-space">    </span>L");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">    </span>`.<span class="Apple-converted-space">        </span>|`--...________.'.<span class="Apple-converted-space">        </span>j <span class="Apple-converted-space">  </span>| <span class="Apple-converted-space">    </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">      </span>`._<span class="Apple-converted-space">    </span>.'<span class="Apple-converted-space">      </span>|<span class="Apple-converted-space">          </span>`. <span class="Apple-converted-space">    </span>.| <span class="Apple-converted-space">  </span>, <span class="Apple-converted-space">    </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">        </span>`--,\\ <span class="Apple-converted-space">      </span>.<span class="Apple-converted-space">            </span>`7\"\"' |<span class="Apple-converted-space">  </span>,<span class="Apple-converted-space">      </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">            </span>` `<span class="Apple-converted-space">      </span>`<span class="Apple-converted-space">            </span>/ <span class="Apple-converted-space">    </span>|<span class="Apple-converted-space">  </span>|<span class="Apple-converted-space">      </span>|<span class="Apple-converted-space">    </span>_,-'\"\"\"`-.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">            </span>\\ `. <span class="Apple-converted-space">    </span>.<span class="Apple-converted-space">          </span>/<span class="Apple-converted-space">      </span>|<span class="Apple-converted-space">  </span>'<span class="Apple-converted-space">      </span>|<span class="Apple-converted-space">  </span>,'<span class="Apple-converted-space">          </span>`.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">              </span>\\<span class="Apple-converted-space">  </span>v.__<span class="Apple-converted-space">  </span>.<span class="Apple-converted-space">        </span>' <span class="Apple-converted-space">      </span>. <span class="Apple-converted-space">  </span>\\<span class="Apple-converted-space">    </span>/| /<span class="Apple-converted-space">              </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">              </span>\\/<span class="Apple-converted-space">    </span>`\"\"\\\"\"\"\"\"\"\"`. <span class="Apple-converted-space">      </span>\\ <span class="Apple-converted-space">  </span>\\<span class="Apple-converted-space">  </span>/.''<span class="Apple-converted-space">                </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">                </span>`<span class="Apple-converted-space">        </span>.<span class="Apple-converted-space">        </span>`._ ___,j.<span class="Apple-converted-space">  </span>`/ .- <span class="Apple-converted-space">      </span>,---. <span class="Apple-converted-space">    </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">                </span>,`-.<span class="Apple-converted-space">      </span>\\ <span class="Apple-converted-space">        </span>.\" <span class="Apple-converted-space">    </span>`.<span class="Apple-converted-space">  </span>|/<span class="Apple-converted-space">        </span>j <span class="Apple-converted-space">    </span>`<span class="Apple-converted-space">    </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">              </span>/<span class="Apple-converted-space">    </span>`. <span class="Apple-converted-space">    </span>\\ <span class="Apple-converted-space">      </span>/ <span class="Apple-converted-space">        </span>\\ / <span class="Apple-converted-space">        </span>| <span class="Apple-converted-space">    </span>/<span class="Apple-converted-space">    </span>j");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">              </span>| <span class="Apple-converted-space">      </span>`-. <span class="Apple-converted-space">  </span>7-.._ .<span class="Apple-converted-space">          </span>|\"<span class="Apple-converted-space">          </span>' <span class="Apple-converted-space">        </span>/");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">              </span>|<span class="Apple-converted-space">          </span>`./_<span class="Apple-converted-space">    </span>`|<span class="Apple-converted-space">          </span>|<span class="Apple-converted-space">            </span>. <span class="Apple-converted-space">    </span>_,'");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">              </span>`. <span class="Apple-converted-space">          </span>/ `----|<span class="Apple-converted-space">          </span>|-............`---'");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">                </span>\\<span class="Apple-converted-space">          </span>\\<span class="Apple-converted-space">      </span>|<span class="Apple-converted-space">          </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">              </span>,' <span class="Apple-converted-space">          </span>) <span class="Apple-converted-space">    </span>`. <span class="Apple-converted-space">        </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">                </span>7____,,..--'<span class="Apple-converted-space">      </span>/<span class="Apple-converted-space">          </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">                                  </span>`---.__,--.'");</p>
<p class="p1"><span class="Apple-converted-space">        </span>typing1 = "water";</p>
<p class="p1"><span class="Apple-converted-space">       </span>}</p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p1"><span class="Apple-converted-space">       </span>if(bhp1 == 39 &amp;&amp; batk1 ==52){</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">              </span>_.--\"\"`-..");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">            </span>,'<span class="Apple-converted-space">          </span>`.");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">          </span>,'<span class="Apple-converted-space">          </span>__<span class="Apple-converted-space">  </span>`.");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">        </span>/|<span class="Apple-converted-space">          </span>\" __ <span class="Apple-converted-space">  </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">        </span>, | <span class="Apple-converted-space">          </span>/ |. <span class="Apple-converted-space">  </span>.");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">        </span>|,'<span class="Apple-converted-space">          </span>!_.'| <span class="Apple-converted-space">  </span>|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">      </span>,' <span class="Apple-converted-space">            </span>' <span class="Apple-converted-space">  </span>| <span class="Apple-converted-space">  </span>|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">    </span>/<span class="Apple-converted-space">              </span>|`--'| <span class="Apple-converted-space">  </span>|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">    </span>|<span class="Apple-converted-space">                </span>`---' <span class="Apple-converted-space">  </span>|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">    </span>. <span class="Apple-converted-space">  </span>, <span class="Apple-converted-space">                  </span>| <span class="Apple-converted-space">                      </span>,\".");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">      </span>._ <span class="Apple-converted-space">    </span>' <span class="Apple-converted-space">          </span>_'<span class="Apple-converted-space">  </span>|<span class="Apple-converted-space">                    </span>, ' \\ `");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">  </span>`.. `.`-...___,...---\"\"<span class="Apple-converted-space">    </span>| <span class="Apple-converted-space">      </span>__,.<span class="Apple-converted-space">        </span>,`\" <span class="Apple-converted-space">  </span>L,|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">  </span>|, `- .`._<span class="Apple-converted-space">        </span>_,-,.' <span class="Apple-converted-space">  </span>.<span class="Apple-converted-space">  </span>__.-'-. /<span class="Apple-converted-space">        </span>. <span class="Apple-converted-space">  </span>,<span class="Apple-converted-space">    </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("-:.. <span class="Apple-converted-space">    </span>`. `-..--_.,.&lt; <span class="Apple-converted-space">      </span>`\"<span class="Apple-converted-space">      </span>/ `.<span class="Apple-converted-space">        </span>`-/ | <span class="Apple-converted-space">  </span>.");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">  </span>`, <span class="Apple-converted-space">        </span>\"\"\"\"' <span class="Apple-converted-space">    </span>`.<span class="Apple-converted-space">              </span>,' <span class="Apple-converted-space">        </span>| <span class="Apple-converted-space">  </span>|<span class="Apple-converted-space">  </span>',,");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">    </span>`.<span class="Apple-converted-space">      </span>'<span class="Apple-converted-space">            </span>'<span class="Apple-converted-space">            </span>/<span class="Apple-converted-space">          </span>'<span class="Apple-converted-space">    </span>|'. |/");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">      </span>`. <span class="Apple-converted-space">  </span>|<span class="Apple-converted-space">              </span>\\ <span class="Apple-converted-space">      </span>_,-' <span class="Apple-converted-space">          </span>| <span class="Apple-converted-space">      </span>''");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">        </span>`._' <span class="Apple-converted-space">              </span>\\ <span class="Apple-converted-space">  </span>\"\\<span class="Apple-converted-space">                </span>.<span class="Apple-converted-space">      </span>|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">          </span>|<span class="Apple-converted-space">                </span>' <span class="Apple-converted-space">    </span>\\<span class="Apple-converted-space">                </span>`._<span class="Apple-converted-space">  </span>,'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">          </span>| <span class="Apple-converted-space">                </span>' <span class="Apple-converted-space">    </span>\\ <span class="Apple-converted-space">                </span>.'|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">          </span>| <span class="Apple-converted-space">                </span>.<span class="Apple-converted-space">      </span>\\<span class="Apple-converted-space">                </span>| |");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">          </span>| <span class="Apple-converted-space">                </span>| <span class="Apple-converted-space">      </span>L<span class="Apple-converted-space">              </span>,' |");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">          </span>` <span class="Apple-converted-space">                </span>| <span class="Apple-converted-space">      </span>| <span class="Apple-converted-space">            </span>/ <span class="Apple-converted-space">  </span>'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">            </span>\\<span class="Apple-converted-space">                </span>| <span class="Apple-converted-space">      </span>| <span class="Apple-converted-space">          </span>,' <span class="Apple-converted-space">  </span>/");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">          </span>,' \\ <span class="Apple-converted-space">              </span>|<span class="Apple-converted-space">  </span>_.._ ,-..___,..-'<span class="Apple-converted-space">    </span>,'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">        </span>/ <span class="Apple-converted-space">    </span>. <span class="Apple-converted-space">            </span>.<span class="Apple-converted-space">      </span>`! <span class="Apple-converted-space">            </span>,j'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">        </span>/ <span class="Apple-converted-space">      </span>`.<span class="Apple-converted-space">          </span>/<span class="Apple-converted-space">        </span>. <span class="Apple-converted-space">          </span>.'/");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">      </span>.<span class="Apple-converted-space">          </span>`. <span class="Apple-converted-space">      </span>/ <span class="Apple-converted-space">        </span>|<span class="Apple-converted-space">        </span>_.'.'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">        </span>`.<span class="Apple-converted-space">          </span>7`'---'<span class="Apple-converted-space">          </span>|------\"'_.'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">      </span>_,.`,_ <span class="Apple-converted-space">    </span>_'<span class="Apple-converted-space">                </span>,''-----\"'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">  </span>_,-_<span class="Apple-converted-space">    </span>' <span class="Apple-converted-space">      </span>`. <span class="Apple-converted-space">    </span>.'<span class="Apple-converted-space">      </span>,\\");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">  </span>-\" /`. <span class="Apple-converted-space">        </span>_,' <span class="Apple-converted-space">    </span>| _<span class="Apple-converted-space">  </span>_<span class="Apple-converted-space">  </span>_.|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">    </span>\"\"--'---\"\"\"\"\"'<span class="Apple-converted-space">        </span>`' '! |! /");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">                            </span>`\" \" -'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>typing1 = "fire";</p>
<p class="p1"><span class="Apple-converted-space">       </span>}</p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("*****************************");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("This is your first pokemon, "+name1+":");</p>
<p class="p1"><span class="Apple-converted-space">       </span>int atk1 = (int)(AtkCalculator(lvlNumeroUno, batk1));</p>
<p class="p1"><span class="Apple-converted-space">       </span>int hp1 = (int)(HPCalculator(lvlNumeroUno,bhp1));</p>
<p class="p1"><span class="Apple-converted-space">       </span>int df1 = (int)(dfCalculator(lvlNumeroUno, bdf1));</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Typing: "+typing1);</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Attack: "+atk1+" <span class="Apple-converted-space">            </span>");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("HP: "+hp1+"<span class="Apple-converted-space">                </span>");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("******************************");</p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p1"><span class="Apple-converted-space">       </span>if(bhp2 == 44 &amp;&amp; batk2 ==48){</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">              </span>_,........__");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">            </span>,-'<span class="Apple-converted-space">            </span>\"`-.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">          </span>,' <span class="Apple-converted-space">                  </span>`-.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">        </span>,'<span class="Apple-converted-space">                        </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">      </span>,' <span class="Apple-converted-space">                          </span>.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">      </span>.'\\ <span class="Apple-converted-space">              </span>,\"\". <span class="Apple-converted-space">      </span>`");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">    </span>._.'| <span class="Apple-converted-space">            </span>/ |<span class="Apple-converted-space">  </span>` <span class="Apple-converted-space">      </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">    </span>| <span class="Apple-converted-space">  </span>|<span class="Apple-converted-space">            </span>`-.'<span class="Apple-converted-space">  </span>|| <span class="Apple-converted-space">      </span>`.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">    </span>| <span class="Apple-converted-space">  </span>|<span class="Apple-converted-space">            </span>'-._,'|| <span class="Apple-converted-space">      </span>| \\");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">    </span>.`.,' <span class="Apple-converted-space">            </span>`..,'.' <span class="Apple-converted-space">      </span>, |`-.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">    </span>l <span class="Apple-converted-space">                      </span>.'`.<span class="Apple-converted-space">  </span>_/<span class="Apple-converted-space">  </span>| <span class="Apple-converted-space">  </span>`.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">    </span>`-.._'- <span class="Apple-converted-space">  </span>,<span class="Apple-converted-space">          </span>_ _' <span class="Apple-converted-space">  </span>-\" \\<span class="Apple-converted-space">  </span>. <span class="Apple-converted-space">    </span>`");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("`.\"\"\"\"\"'-.`-...,---------',' <span class="Apple-converted-space">        </span>`. `....__.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(".'<span class="Apple-converted-space">        </span>`\"-..___<span class="Apple-converted-space">      </span>__,'\\<span class="Apple-converted-space">          </span>\\<span class="Apple-converted-space">  </span>\\ <span class="Apple-converted-space">    </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("\\_ .<span class="Apple-converted-space">          </span>| <span class="Apple-converted-space">  </span>`\"\"\"\"'<span class="Apple-converted-space">    </span>`. <span class="Apple-converted-space">          </span>. \\ <span class="Apple-converted-space">    </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">  </span>`.<span class="Apple-converted-space">          </span>|<span class="Apple-converted-space">              </span>`.<span class="Apple-converted-space">          </span>|<span class="Apple-converted-space">  </span>. <span class="Apple-converted-space">    </span>L");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">    </span>`.<span class="Apple-converted-space">        </span>|`--...________.'.<span class="Apple-converted-space">        </span>j <span class="Apple-converted-space">  </span>| <span class="Apple-converted-space">    </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">      </span>`._<span class="Apple-converted-space">    </span>.'<span class="Apple-converted-space">      </span>|<span class="Apple-converted-space">          </span>`. <span class="Apple-converted-space">    </span>.| <span class="Apple-converted-space">  </span>, <span class="Apple-converted-space">    </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">        </span>`--,\\ <span class="Apple-converted-space">      </span>.<span class="Apple-converted-space">            </span>`7\"\"' |<span class="Apple-converted-space">  </span>,<span class="Apple-converted-space">      </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">            </span>` `<span class="Apple-converted-space">      </span>`<span class="Apple-converted-space">            </span>/ <span class="Apple-converted-space">    </span>|<span class="Apple-converted-space">  </span>|<span class="Apple-converted-space">      </span>|<span class="Apple-converted-space">    </span>_,-'\"\"\"`-.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">            </span>\\ `. <span class="Apple-converted-space">    </span>.<span class="Apple-converted-space">          </span>/<span class="Apple-converted-space">      </span>|<span class="Apple-converted-space">  </span>'<span class="Apple-converted-space">      </span>|<span class="Apple-converted-space">  </span>,'<span class="Apple-converted-space">          </span>`.");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">              </span>\\<span class="Apple-converted-space">  </span>v.__<span class="Apple-converted-space">  </span>.<span class="Apple-converted-space">        </span>' <span class="Apple-converted-space">      </span>. <span class="Apple-converted-space">  </span>\\<span class="Apple-converted-space">    </span>/| /<span class="Apple-converted-space">              </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">              </span>\\/<span class="Apple-converted-space">    </span>`\"\"\\\"\"\"\"\"\"\"`. <span class="Apple-converted-space">      </span>\\ <span class="Apple-converted-space">  </span>\\<span class="Apple-converted-space">  </span>/.''<span class="Apple-converted-space">                </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">                </span>`<span class="Apple-converted-space">        </span>.<span class="Apple-converted-space">        </span>`._ ___,j.<span class="Apple-converted-space">  </span>`/ .- <span class="Apple-converted-space">      </span>,---. <span class="Apple-converted-space">    </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">                </span>,`-.<span class="Apple-converted-space">      </span>\\ <span class="Apple-converted-space">        </span>.\" <span class="Apple-converted-space">    </span>`.<span class="Apple-converted-space">  </span>|/<span class="Apple-converted-space">        </span>j <span class="Apple-converted-space">    </span>`<span class="Apple-converted-space">    </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">              </span>/<span class="Apple-converted-space">    </span>`. <span class="Apple-converted-space">    </span>\\ <span class="Apple-converted-space">      </span>/ <span class="Apple-converted-space">        </span>\\ / <span class="Apple-converted-space">        </span>| <span class="Apple-converted-space">    </span>/<span class="Apple-converted-space">    </span>j");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">              </span>| <span class="Apple-converted-space">      </span>`-. <span class="Apple-converted-space">  </span>7-.._ .<span class="Apple-converted-space">          </span>|\"<span class="Apple-converted-space">          </span>' <span class="Apple-converted-space">        </span>/");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">              </span>|<span class="Apple-converted-space">          </span>`./_<span class="Apple-converted-space">    </span>`|<span class="Apple-converted-space">          </span>|<span class="Apple-converted-space">            </span>. <span class="Apple-converted-space">    </span>_,'");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">              </span>`. <span class="Apple-converted-space">          </span>/ `----|<span class="Apple-converted-space">          </span>|-............`---'");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">                </span>\\<span class="Apple-converted-space">          </span>\\<span class="Apple-converted-space">      </span>|<span class="Apple-converted-space">          </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println(" <span class="Apple-converted-space">              </span>,' <span class="Apple-converted-space">          </span>) <span class="Apple-converted-space">    </span>`. <span class="Apple-converted-space">        </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">                </span>7____,,..--'<span class="Apple-converted-space">      </span>/<span class="Apple-converted-space">          </span>|");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("<span class="Apple-converted-space">                                  </span>`---.__,--.'");</p>
<p class="p1"><span class="Apple-converted-space">        </span>typing2 = "water";</p>
<p class="p1"><span class="Apple-converted-space">       </span>}</p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p1"><span class="Apple-converted-space">       </span>if(bhp2 == 39 &amp;&amp; batk2 ==52){</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">              </span>_.--\"\"`-..");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">            </span>,'<span class="Apple-converted-space">          </span>`.");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">          </span>,'<span class="Apple-converted-space">          </span>__<span class="Apple-converted-space">  </span>`.");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">        </span>/|<span class="Apple-converted-space">          </span>\" __ <span class="Apple-converted-space">  </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">        </span>, | <span class="Apple-converted-space">          </span>/ |. <span class="Apple-converted-space">  </span>.");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">        </span>|,'<span class="Apple-converted-space">          </span>!_.'| <span class="Apple-converted-space">  </span>|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">      </span>,' <span class="Apple-converted-space">            </span>' <span class="Apple-converted-space">  </span>| <span class="Apple-converted-space">  </span>|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">    </span>/<span class="Apple-converted-space">              </span>|`--'| <span class="Apple-converted-space">  </span>|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">    </span>|<span class="Apple-converted-space">                </span>`---' <span class="Apple-converted-space">  </span>|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">    </span>. <span class="Apple-converted-space">  </span>, <span class="Apple-converted-space">                  </span>| <span class="Apple-converted-space">                      </span>,\".");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">      </span>._ <span class="Apple-converted-space">    </span>' <span class="Apple-converted-space">          </span>_'<span class="Apple-converted-space">  </span>|<span class="Apple-converted-space">                    </span>, ' \\ `");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">  </span>`.. `.`-...___,...---\"\"<span class="Apple-converted-space">    </span>| <span class="Apple-converted-space">      </span>__,.<span class="Apple-converted-space">        </span>,`\" <span class="Apple-converted-space">  </span>L,|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">  </span>|, `- .`._<span class="Apple-converted-space">        </span>_,-,.' <span class="Apple-converted-space">  </span>.<span class="Apple-converted-space">  </span>__.-'-. /<span class="Apple-converted-space">        </span>. <span class="Apple-converted-space">  </span>,<span class="Apple-converted-space">    </span>\\");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("-:.. <span class="Apple-converted-space">    </span>`. `-..--_.,.&lt; <span class="Apple-converted-space">      </span>`\"<span class="Apple-converted-space">      </span>/ `.<span class="Apple-converted-space">        </span>`-/ | <span class="Apple-converted-space">  </span>.");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">  </span>`, <span class="Apple-converted-space">        </span>\"\"\"\"' <span class="Apple-converted-space">    </span>`.<span class="Apple-converted-space">              </span>,' <span class="Apple-converted-space">        </span>| <span class="Apple-converted-space">  </span>|<span class="Apple-converted-space">  </span>',,");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">    </span>`.<span class="Apple-converted-space">      </span>'<span class="Apple-converted-space">            </span>'<span class="Apple-converted-space">            </span>/<span class="Apple-converted-space">          </span>'<span class="Apple-converted-space">    </span>|'. |/");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">      </span>`. <span class="Apple-converted-space">  </span>|<span class="Apple-converted-space">              </span>\\ <span class="Apple-converted-space">      </span>_,-' <span class="Apple-converted-space">          </span>| <span class="Apple-converted-space">      </span>''");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">        </span>`._' <span class="Apple-converted-space">              </span>\\ <span class="Apple-converted-space">  </span>\"\\<span class="Apple-converted-space">                </span>.<span class="Apple-converted-space">      </span>|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">          </span>|<span class="Apple-converted-space">                </span>' <span class="Apple-converted-space">    </span>\\<span class="Apple-converted-space">                </span>`._<span class="Apple-converted-space">  </span>,'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">          </span>| <span class="Apple-converted-space">                </span>' <span class="Apple-converted-space">    </span>\\ <span class="Apple-converted-space">                </span>.'|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">          </span>| <span class="Apple-converted-space">                </span>.<span class="Apple-converted-space">      </span>\\<span class="Apple-converted-space">                </span>| |");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">          </span>| <span class="Apple-converted-space">                </span>| <span class="Apple-converted-space">      </span>L<span class="Apple-converted-space">              </span>,' |");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">          </span>` <span class="Apple-converted-space">                </span>| <span class="Apple-converted-space">      </span>| <span class="Apple-converted-space">            </span>/ <span class="Apple-converted-space">  </span>'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">            </span>\\<span class="Apple-converted-space">                </span>| <span class="Apple-converted-space">      </span>| <span class="Apple-converted-space">          </span>,' <span class="Apple-converted-space">  </span>/");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">          </span>,' \\ <span class="Apple-converted-space">              </span>|<span class="Apple-converted-space">  </span>_.._ ,-..___,..-'<span class="Apple-converted-space">    </span>,'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">        </span>/ <span class="Apple-converted-space">    </span>. <span class="Apple-converted-space">            </span>.<span class="Apple-converted-space">      </span>`! <span class="Apple-converted-space">            </span>,j'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">        </span>/ <span class="Apple-converted-space">      </span>`.<span class="Apple-converted-space">          </span>/<span class="Apple-converted-space">        </span>. <span class="Apple-converted-space">          </span>.'/");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">      </span>.<span class="Apple-converted-space">          </span>`. <span class="Apple-converted-space">      </span>/ <span class="Apple-converted-space">        </span>|<span class="Apple-converted-space">        </span>_.'.'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">        </span>`.<span class="Apple-converted-space">          </span>7`'---'<span class="Apple-converted-space">          </span>|------\"'_.'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">      </span>_,.`,_ <span class="Apple-converted-space">    </span>_'<span class="Apple-converted-space">                </span>,''-----\"'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">  </span>_,-_<span class="Apple-converted-space">    </span>' <span class="Apple-converted-space">      </span>`. <span class="Apple-converted-space">    </span>.'<span class="Apple-converted-space">      </span>,\\");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(" <span class="Apple-converted-space">  </span>-\" /`. <span class="Apple-converted-space">        </span>_,' <span class="Apple-converted-space">    </span>| _<span class="Apple-converted-space">  </span>_<span class="Apple-converted-space">  </span>_.|");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">    </span>\"\"--'---\"\"\"\"\"'<span class="Apple-converted-space">        </span>`' '! |! /");</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println("<span class="Apple-converted-space">                            </span>`\" \" -'");</p>
<p class="p1"><span class="Apple-converted-space">           </span>typing2 = "fire";</p>
<p class="p1"><span class="Apple-converted-space">       </span>}</p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("*****************************");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("This is your second pokemon, "+name2+":");</p>
<p class="p1"><span class="Apple-converted-space">       </span>int atk2 = (int)(AtkCalculator(lvlNumeroDos, batk2));</p>
<p class="p1"><span class="Apple-converted-space">       </span>int hp2 = (int)(HPCalculator(lvlNumeroDos,bhp2));</p>
<p class="p1"><span class="Apple-converted-space">       </span>int df2 = (int)(dfCalculator(lvlNumeroDos, bdf2));</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Typing: "+typing2);</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("Attack: "+atk2+" <span class="Apple-converted-space">            </span>");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("HP: "+hp2+"<span class="Apple-converted-space">                </span>");</p>
<p class="p1"><span class="Apple-converted-space">       </span>System.out.println("******************************");</p>
<p class="p1"><span class="Apple-converted-space">       </span>while(hp1&gt;0 &amp;&amp; hp2&gt;0){</p>
<p class="p1"><span class="Apple-converted-space">            </span>//random damage generator</p>
<p class="p1"><span class="Apple-converted-space">            </span>double random = Math.random();</p>
<p class="p1"><span class="Apple-converted-space">            </span>while(random&lt;0.85){</p>
<p class="p1"><span class="Apple-converted-space">            </span>random = Math.random();</p>
<p class="p1"><span class="Apple-converted-space">            </span>}</p>
<p class="p2"><span class="Apple-converted-space">            </span></p>
<p class="p1"><span class="Apple-converted-space">            </span>random=(int)(random*100);</p>
<p class="p1"><span class="Apple-converted-space">            </span>random=(double)(random/100);</p>
<p class="p1"><span class="Apple-converted-space">            </span>hp1=hp1-(int)(random*((2*lvlNumeroDos+10)/250 + (atk2/df2) + 2));</p>
<p class="p1"><span class="Apple-converted-space">            </span>System.out.println(name1+" is down to "+hp1+" hp");</p>
<p class="p2"><span class="Apple-converted-space">            </span></p>
<p class="p2"><span class="Apple-converted-space">            </span></p>
<p class="p1"><span class="Apple-converted-space">            </span>random = Math.random();</p>
<p class="p1"><span class="Apple-converted-space">            </span>while(random&lt;0.85){</p>
<p class="p1"><span class="Apple-converted-space">            </span>random = Math.random();</p>
<p class="p1"><span class="Apple-converted-space">            </span>}</p>
<p class="p1"><span class="Apple-converted-space">            </span>random=(int)(random*100);</p>
<p class="p1"><span class="Apple-converted-space">            </span>random=(double)(random/100);</p>
<p class="p1"><span class="Apple-converted-space">            </span>hp2 = hp2-(int)(random*((2*lvlNumeroUno+10)/250 + (atk1/df1) + 2));</p>
<p class="p1"><span class="Apple-converted-space">            </span>System.out.println(name2+" is down to "+hp2+" hp");</p>
<p class="p2"><span class="Apple-converted-space">            </span></p>
<p class="p2"><span class="Apple-converted-space">            </span></p>
<p class="p2"><span class="Apple-converted-space">            </span></p>
<p class="p2"><span class="Apple-converted-space">            </span></p>
<p class="p1"><span class="Apple-converted-space">       </span>}</p>
<p class="p1"><span class="Apple-converted-space">       </span>if(hp1&gt;0){</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(name1+" wins!");</p>
<p class="p1"><span class="Apple-converted-space">       </span>}</p>
<p class="p1"><span class="Apple-converted-space">       </span>if(hp2&gt;0){</p>
<p class="p1"><span class="Apple-converted-space">           </span>System.out.println(name2+ "wins!");</p>
<p class="p1"><span class="Apple-converted-space">       </span>}</p>
<p class="p2"><span class="Apple-converted-space">       </span></p>
<p class="p1"><span class="Apple-converted-space">    </span>}</p>
<p class="p1">}</p>
</body>
</html>
